spring:
  data:
    mongodb:
      username: ankit
      password: ankit
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090